### ISSUE TITLE
html2text: error: unrecognized arguments: -from_encoding

### ISSUE THREAD

**Issue by tmarkov** [wofr06/lesspipe.sh#60]
I'm using Arch linux. I have installed `lesspipe` and `python-html2text`. When using `lesspipe` I get

```
> lesspipe.sh file.pdf  
==> append : to filename to view the PDF source
usage: html2text [-h] [--default-image-alt DEFAULT_IMAGE_ALT] [--pad-tables] [--no-wrap-links] [--wrap-list-items] [--ignore-emphasis]
                 [--reference-links] [--ignore-links] [--protect-links] [--ignore-images] [--images-as-html] [--images-to-alt]
                 [--images-with-size] [-g] [-d] [-e] [-b BODY_WIDTH] [-i LIST_INDENT] [-s] [--escape-all] [--bypass-tables] [--ignore-tables]
                 [--single-line-break] [--unicode-snob] [--no-automatic-links] [--no-skip-internal-links] [--links-after-para] [--mark-code]
                 [--decode-errors DECODE_ERRORS] [--open-quote OPEN_QUOTE] [--close-quote CLOSE_QUOTE] [--version]
                 [filename] [encoding]
html2text: error: unrecognized arguments: -from_encoding
```

I've changed `lesspipe.sh` [here](https://github.com/wofr06/lesspipe/blob/409f2db85803b66206df5bc7ec908be119aab7d6/lesspipe.sh#L538) as follows to fix the issue on my system.

```
 elif cmd_exist html2text; then
    html2text -utf8 "$1" 2>/dev/null || html2text "$1" utf8; 
``

Note that in my version reading from stdin is also indicated by filename "-" before the encoding.

**Comment by lemen** [comment]
The  problem with `python-html2text` on Arch Linux is that `lesspipe.sh`  does not adhere to it's syntax/options i.e. missing the `-utf8` flag. 
This seems to be introduced for compatibility with OpenSuse in commit  0c077bd231e74b496b1be505ce3b221b116c42d9.

Could you also specify which version of `html2text` you are targeting as there are numerous differing implementations out there. The README only mentions [http://www.mbayer.de/html2text](http://www.mbayer.de/html2text) which provides the `-from_encoding` option. 

Edit: Link

**Comment by tmarkov** [comment]
lesspipe tries both `-utf8` flag, and a `-from-encoding` option. What I'm reporting here is that Arch's html2text utility (`python-html2text`, https://pypi.org/project/html2text/) doesn't support either of these two variants, and instead takes `html2text [filename] [encoding]`.

So lesspipe could try a third command:
```
    if [[ "$1" = - ]]; then html2text -utf8 2>/dev/null ||
      html2text -from_encoding utf-8 ||  html2text - utf-8
    else html2text -utf8 "$1" 2>/dev/null ||
      html2text -from_encoding utf-8 "$1" || html2text "$1" utf8; fi
```

**Comment by lemen** [comment]
After some digging into [the packaging world of OpenSuse](https://build.opensuse.org/package/show/openSUSE:Factory/html2text) I dicovered
[1] OpenSuse uses [a fork](https://github.com/grobian/html2text) of [mbayers ](http://www.mbayer.de/html2text) `html2text`
[2] that the `-utf8` flag comes from a [debian patch](https://sources.debian.org/patches/html2text/1.3.2a-28/500-utf8-support.patch/)
So the new question becomes whether/how this project wants to deal with differing `html2text` implementations?
As outlined already above this can be done by including additional calls to `html2text`. 
At the moment `lesspipe` seems to only support mbayers implementation and it's derivatives. 

Moreover it seems that OpenSuse [started to ship](https://build.opensuse.org/package/view_file/openSUSE:Factory/html2text/html2text.spec?expand=1) their executable as `html2text-cpp`. I don't use OpenSuse so I can not confirm this at the moment. This is done to avoid conflicts with their `python3-html2text`. This will probably lead to a similar breakage on their system as well.

**Comment by wofr06** [comment]
Dear all,

if it turns out that the original html2text is not fancy enough and 
people are tempted to implement new features and quirks and backward 
compatibility is not one of their goals, then I would propose to not use 
any longer html2text but prefer lynx, links, elinks or w3m in the first 
place or support just one version of html2text and then fallback to the 
aforementioned list.

In the end lesspipe is meant to support people getting some more 
readable content from a file, not necessarily a very polished one. 
Another option would be to completely avoid html2text and use the 
heavyweight pandoc, which comes already with a lot converters and can 
output plain text.

ny 2 cents.
Wolfgang

Am 04.10.21 um 16:59 schrieb lemen:

**Comment by tmarkov** [comment]
I agree that with multiple non-backwards-compatible versions, it's somewhat messy trying to support them all (I opened an issue instead of a PR was because I wasn't sure what the best approach would be). Supporting just one, and either moving it lowest priority or adding a fallback is cleaner indeed. Though I can see some issues with that - namely, if the wrong html2text is installed, and no other html parsing utility is present, then line 243 will wrongly decide that html parsing is available (I don't know if that's really bad, too many if/elses to track them all). On the other hand, just removing support will make lesspipe not backwards compatible.

**Comment by wofr06** [comment]
See the comment on issue #68, with the 2.00 lesspipe.sh this should be fixed

**Comment by callegar** [comment]
Please reopen: still getting `html2text: error: unrecognized arguments: -utf8` with 2.07 on manjaro (arch).

**Comment by wofr06** [comment]
With the recent fix issues #60 and #68 should be finally resolved. html2text is now used as a last resort if other utilities like lynx or w3m are not installed. For compatibility reasons no options to html2text are given any longer.
