### ISSUE TITLE
lesspipe: stable 2.01 (bottled) emits bash: _init_completion: command not found errors

### ISSUE THREAD

**Issue by glensc** [wofr06/lesspipe.sh#74]
```
less f<Tab>
bash: _init_completion: command not found
```

seems the problem is that completions from this package assume bash-completions 2.x unconditionally:
- https://github.com/wofr06/lesspipe/blob/e3d43979442a49d959160d18223ed7d18d64fdcc/less_completion#L6

refs:
- https://github.com/wofr06/lesspipe/commit/37b51511a33983041b64bbc9d5cec84a2fa75f7f

typically this is solved (in other packages present in brew):

`$ grep -rF _init_completion /usr/local/etc/bash_completion.d/* /usr/local/share/bash-completion/completions/* -l`

```
/usr/local/etc/bash_completion.d/chezmoi-completion.bash
/usr/local/etc/bash_completion.d/gh
/usr/local/etc/bash_completion.d/kubectl
/usr/local/etc/bash_completion.d/less_completion
/usr/local/etc/bash_completion.d/mas
/usr/local/etc/bash_completion.d/mosh
/usr/local/etc/bash_completion.d/podman
/usr/local/etc/bash_completion.d/rclone
/usr/local/etc/bash_completion.d/skaffold
/usr/local/etc/bash_completion.d/tmux
/usr/local/etc/bash_completion.d/yarn
/usr/local/etc/bash_completion.d/yq
/usr/local/share/bash-completion/completions/cmake
/usr/local/share/bash-completion/completions/cpack
/usr/local/share/bash-completion/completions/ctest
```

example:
```bash

# Macs have bash3 for which the bash-completion package doesn't include
# _init_completion. This is a minimal version of that function.
__gh_init_completion()
{
    COMPREPLY=()
    _get_comp_words_by_ref "$@" cur prev words cword
}

...
    # Call _init_completion from the bash-completion package
    # to prepare the arguments properly
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -n "=:" || return
    else
        __gh_init_completion -n "=:" || return
    fi
```

- https://github.com/spf13/cobra/blob/e04ec725508c760e70263b031e5697c232d5c3fa/bash_completionsV2.go#L32-L38
- https://github.com/spf13/cobra/blob/e04ec725508c760e70263b031e5697c232d5c3fa/bash_completionsV2.go#L281-L287

**Comment by glensc** [comment]
or perhaps simple as:


```bash
# cat /usr/local/etc/bash_completion.d/mas

_mas() {
  local cur prev words cword
  if declare -F _init_completions >/dev/null 2>&1; then
    _init_completion
  else
    COMPREPLY=()
    _get_comp_words_by_ref cur prev words cword
  fi
  if [[ $cword -eq 1 ]]; then
    COMPREPLY=($(compgen -W "$(mas help | tail -n +3 | awk '{print $1}')" -- "$cur"))
    return 0
  fi
}

complete -F _mas mas
```

**Comment by glensc** [comment]
or perhaps:

```bash

__mosh_init_completion()
{
    if declare -F _init_completions >/dev/null 2>&1; then
        _init_completion
    else
        COMPREPLY=()
        _get_comp_words_by_ref cur prev words cword
    fi
}

_mosh () {
    local cur

    __mosh_init_completion || return
...
```

**Comment by wofr06** [comment]
Thanks, I implemented one of your suggestions

**Comment by glensc** [comment]
you forgot to cross link things:
- https://github.com/wofr06/lesspipe/commit/90b5bb2ad2d26d5637282d36f21d888667a89ba7
